//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlBalance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlBalance.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string About1333 {
            get {
                return ResourceManager.GetString("About1333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь, что контроллер стоит неподвижно на ровной поверхности крышкой вверх. Продолжить?.
        /// </summary>
        internal static string AccCalibrate {
            get {
                return ResourceManager.GetString("AccCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автонастройка завершена.
        /// </summary>
        internal static string AutosettingsCompleted {
            get {
                return ResourceManager.GetString("AutosettingsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка закончена, не забудьте сохранить изменения в памяти..
        /// </summary>
        internal static string AutosettingsCompletedMSG {
            get {
                return ResourceManager.GetString("AutosettingsCompletedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите ручку тормоза до упора и выберите ОК, для пропуска выберите NO.
        /// </summary>
        internal static string BreakCalibration {
            get {
                return ResourceManager.GetString("BreakCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось установить соединение. Проверьте BlueTooth и откройте порт заново.
        /// </summary>
        internal static string CannotToConnect {
            get {
                return ResourceManager.GetString("CannotToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарядка завершена.
        /// </summary>
        internal static string ChargingCompleted {
            get {
                return ResourceManager.GetString("ChargingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка контрольной суммы.
        /// </summary>
        internal static string CHKErr {
            get {
                return ResourceManager.GetString("CHKErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жесткий режим.
        /// </summary>
        internal static string ComplementaryMode {
            get {
                return ResourceManager.GetString("ComplementaryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение установлено.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с устройством установлена.
        /// </summary>
        internal static string ConnectedController {
            get {
                return ResourceManager.GetString("ConnectedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с ведущим: ЕСТЬ.
        /// </summary>
        internal static string ConnectedWithMaster {
            get {
                return ResourceManager.GetString("ConnectedWithMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка передачи 2. Проверьте BlueTooth и откройте порт заново.
        /// </summary>
        internal static string ConnectionErr2 {
            get {
                return ResourceManager.GetString("ConnectionErr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроллер не обнаружен.
        /// </summary>
        internal static string ControllerNotDetected {
            get {
                return ResourceManager.GetString("ControllerNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать настройки режима 1 в режимы 2 и 3?.
        /// </summary>
        internal static string CopySettings {
            get {
                return ResourceManager.GetString("CopySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирование настроек.
        /// </summary>
        internal static string CopySettingsZ {
            get {
                return ResourceManager.GetString("CopySettingsZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калибровка датчика тока . . ..
        /// </summary>
        internal static string CurrSenorCalibrate {
            get {
                return ResourceManager.GetString("CurrSenorCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калибровка датчика тока закончена..
        /// </summary>
        internal static string CurrSenorCalibrateFinished {
            get {
                return ResourceManager.GetString("CurrSenorCalibrateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для защиты контроллера ограничения тока будут снижены.
        /// </summary>
        internal static string DecreaseCurrentSettings {
            get {
                return ResourceManager.GetString("DecreaseCurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задержка 1 сек..
        /// </summary>
        internal static string Delay1s {
            get {
                return ResourceManager.GetString("Delay1s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Задержка. +++.
        /// </summary>
        internal static string DelayU {
            get {
                return ResourceManager.GetString("DelayU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключено.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с устройством потеряна. Проверьте BlueTooth и откройте порт заново.
        /// </summary>
        internal static string DisconnectedController {
            get {
                return ResourceManager.GetString("DisconnectedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с ведущим: НЕТ.
        /// </summary>
        internal static string DisconnectedWithMaster {
            get {
                return ResourceManager.GetString("DisconnectedWithMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен предельных уровень ручки газа (2).
        /// </summary>
        internal static string DisconnectedZeroWire {
            get {
                return ResourceManager.GetString("DisconnectedZeroWire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неисправность акселерометра/гироскопа (10).
        /// </summary>
        internal static string Err_CRERR_GYROACC_DISCONNECTED {
            get {
                return ResourceManager.GetString("Err_CRERR_GYROACC_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потеря связи с ведущим (11).
        /// </summary>
        internal static string Err_CRERR_MASTER_DISCONNECTED {
            get {
                return ResourceManager.GetString("Err_CRERR_MASTER_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резкое увеличение ШИМ.
        /// </summary>
        internal static string Err_CRERR_PWM_CHANGED_HIGH {
            get {
                return ResourceManager.GetString("Err_CRERR_PWM_CHANGED_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 255. Произведите настройку сдвига фаз вручную.
        /// </summary>
        internal static string Error255 {
            get {
                return ResourceManager.GetString("Error255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 256. Произведите настройку сдвига фаз вручную.
        /// </summary>
        internal static string Error256 {
            get {
                return ResourceManager.GetString("Error256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перегрев контроллера (5).
        /// </summary>
        internal static string FETsOverTemperature {
            get {
                return ResourceManager.GetString("FETsOverTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определение оптимальной....
        /// </summary>
        internal static string FindingOptimal {
            get {
                return ResourceManager.GetString("FindingOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия прошивки: Нет соединения с контроллером.
        /// </summary>
        internal static string FirmwareNotConnected {
            get {
                return ResourceManager.GetString("FirmwareNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия прошивки:.
        /// </summary>
        internal static string FirmwareVer {
            get {
                return ResourceManager.GetString("FirmwareVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружено рабочих комбинаций:.
        /// </summary>
        internal static string FoundOrders {
            get {
                return ResourceManager.GetString("FoundOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь, что контроллер стоит неподвижно. Продолжить?.
        /// </summary>
        internal static string GyroCalibr {
            get {
                return ResourceManager.GetString("GyroCalibr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВАЖНО!!!.
        /// </summary>
        internal static string GyroCalibrTittle {
            get {
                return ResourceManager.GetString("GyroCalibrTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокий уровень сигнала с ручки газа после автонастройки (9).
        /// </summary>
        internal static string HighLevelFromThrottleAfterAutoSettings {
            get {
                return ResourceManager.GetString("HighLevelFromThrottleAfterAutoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний порог ручки тормоза:.
        /// </summary>
        internal static string HighLevelHallBreak {
            get {
                return ResourceManager.GetString("HighLevelHallBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокий уровень сигнала с ручки газа по включению (1).
        /// </summary>
        internal static string HighLevelThrottleOn {
            get {
                return ResourceManager.GetString("HighLevelThrottleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличение ШИМ....
        /// </summary>
        internal static string IncPWM {
            get {
                return ResourceManager.GetString("IncPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Inform {
            get {
                return ResourceManager.GetString("Inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to км/ч.
        /// </summary>
        internal static string KMH {
            get {
                return ResourceManager.GetString("KMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАБЛОКИРОВАТЬ.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижний порог ручки тормоза:.
        /// </summary>
        internal static string LowLevelHallBreak {
            get {
                return ResourceManager.GetString("LowLevelHallBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижний порог ручки газа:.
        /// </summary>
        internal static string LowLevelThrottle {
            get {
                return ResourceManager.GetString("LowLevelThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка порогов ручки тормоза: нижний выше верхнего..
        /// </summary>
        internal static string LowMoreHighBreak {
            get {
                return ResourceManager.GetString("LowMoreHighBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка порогов ручки тормоза: нижний выше верхнего. Произведите настройку порогов ручки тормоза вручную.
        /// </summary>
        internal static string LowMoreHighBreakMSG {
            get {
                return ResourceManager.GetString("LowMoreHighBreakMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка порогов ручки газа: нижний выше верхнего..
        /// </summary>
        internal static string LowMoreHighThrottle {
            get {
                return ResourceManager.GetString("LowMoreHighThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка порогов ручки газа: нижний выше верхнего. Произведите настройку порогов ручки газа вручную.
        /// </summary>
        internal static string LowMoreHighThrottleMSG {
            get {
                return ResourceManager.GetString("LowMoreHighThrottleMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если двигатель вращается нормально, нажмите \&quot;ОК\&quot;, если нет, то выберите \&quot;NO\&quot; и выполните настройку вручную.
        /// </summary>
        internal static string MotorMovingOkNo {
            get {
                return ResourceManager.GetString("MotorMovingOkNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перегрев двигателя (6).
        /// </summary>
        internal static string MotorOverheated {
            get {
                return ResourceManager.GetString("MotorOverheated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция невозможна, т.к. включен режим моноцилка.
        /// </summary>
        internal static string OperationNotPossible {
            get {
                return ResourceManager.GetString("OperationNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки загружены.
        /// </summary>
        internal static string OptionsLoaded {
            get {
                return ResourceManager.GetString("OptionsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки не сохранены.
        /// </summary>
        internal static string OptionsNotSaved {
            get {
                return ResourceManager.GetString("OptionsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки сохранены.
        /// </summary>
        internal static string OptionsSaved {
            get {
                return ResourceManager.GetString("OptionsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определен рабочий порядок фаз:.
        /// </summary>
        internal static string OrderFound {
            get {
                return ResourceManager.GetString("OrderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочие комбинации фаз не обнаружены.
        /// </summary>
        internal static string OrderNotDetected {
            get {
                return ResourceManager.GetString("OrderNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обнаружены рабочие комбинации фаз. Проверьте проводку или попробуйте настроить вручную..
        /// </summary>
        internal static string OrderNotDetectedMSG {
            get {
                return ResourceManager.GetString("OrderNotDetectedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт закрыт.
        /// </summary>
        internal static string PortClosed {
            get {
                return ResourceManager.GetString("PortClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт открыт.
        /// </summary>
        internal static string PortOpened {
            get {
                return ResourceManager.GetString("PortOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Скважность ШИМ увеличена.
        /// </summary>
        internal static string PWMIncreased {
            get {
                return ResourceManager.GetString("PWMIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таймаут чтения порта. Проверьте BlueTooth и откройте порт заново.
        /// </summary>
        internal static string ReadTimeout {
            get {
                return ResourceManager.GetString("ReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить автонастройку заново?.
        /// </summary>
        internal static string RestartQ {
            get {
                return ResourceManager.GetString("RestartQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы двигателя \&quot;Sin2\&quot; после окончания заряда будет отключен. Для его включения нужно будет перезапустить контроллер или установить флажок \&quot;Sin2\&quot; на вкладке \&quot;Двигатель\&quot;.
        /// </summary>
        internal static string RestartSin2 {
            get {
                return ResourceManager.GetString("RestartSin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат: ---OK---.
        /// </summary>
        internal static string ResultOK {
            get {
                return ResourceManager.GetString("ResultOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат: неудачный.
        /// </summary>
        internal static string ResultUnsuccessful {
            get {
                return ResourceManager.GetString("ResultUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость на синусе ограничена 40км/ч. Если выше, то переключение на трапецию..
        /// </summary>
        internal static string SpeedLimitSin10kHz {
            get {
                return ResourceManager.GetString("SpeedLimitSin10kHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость на синусе ограничена 20км/ч. Если выше, то переключение на трапецию..
        /// </summary>
        internal static string SpeedLimitSin5kHz {
            get {
                return ResourceManager.GetString("SpeedLimitSin5kHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------  Старт автонастройки  ----------.
        /// </summary>
        internal static string StartingAutosettings {
            get {
                return ResourceManager.GetString("StartingAutosettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка....
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Остановка.
        /// </summary>
        internal static string Stp {
            get {
                return ResourceManager.GetString("Stp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите ручку газа до упора и выберите ОК, для пропуска выберите NO.
        /// </summary>
        internal static string ThrottleCalibration {
            get {
                return ResourceManager.GetString("ThrottleCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний порог ручки газа:.
        /// </summary>
        internal static string ThrottleHighLevel {
            get {
                return ResourceManager.GetString("ThrottleHighLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port read timeout.  Check the BlueTooth and reopen the port..
        /// </summary>
        internal static string TMout {
            get {
                return ResourceManager.GetString("TMout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком высокий порог отпущенной ручки тормоза.
        /// </summary>
        internal static string TooHighBreak {
            get {
                return ResourceManager.GetString("TooHighBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком высокий порог отпущенной ручки тормоза. Произведите настройку порогов ручки тормоза вручную.
        /// </summary>
        internal static string TooHighBreakMSG {
            get {
                return ResourceManager.GetString("TooHighBreakMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком высокий порог отпущенной ручки газа.
        /// </summary>
        internal static string TooHighThrottle {
            get {
                return ResourceManager.GetString("TooHighThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком высокий порог отпущенной ручки газа. Произведите настройку порогов ручки газа вручную.
        /// </summary>
        internal static string TooHighThrottleMsg {
            get {
                return ResourceManager.GetString("TooHighThrottleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен максимальный порог напряжения батареи (8).
        /// </summary>
        internal static string TooHighVoltage {
            get {
                return ResourceManager.GetString("TooHighVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком низкий порог нажатой ручки тормоза.
        /// </summary>
        internal static string TooLowBreak {
            get {
                return ResourceManager.GetString("TooLowBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком низкий порог нажатой ручки тормоза. Произведите настройку порогов ручки тормоза вручную.
        /// </summary>
        internal static string TooLowBreakMSG {
            get {
                return ResourceManager.GetString("TooLowBreakMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком низкий порог нажатой ручки газа.
        /// </summary>
        internal static string TooLowThrottle {
            get {
                return ResourceManager.GetString("TooLowThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком низкий порог нажатой ручки газа. Произведите настройку порогов ручки газа вручную..
        /// </summary>
        internal static string TooLowThrottleMSG {
            get {
                return ResourceManager.GetString("TooLowThrottleMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Низкое напряжение батареи (3).
        /// </summary>
        internal static string TooLowVoltage {
            get {
                return ResourceManager.GetString("TooLowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        internal static string ToStop {
            get {
                return ResourceManager.GetString("ToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РАЗБЛОКИРОВАТЬ.
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Векторный, обычный, фильтр отключен, режим моноцикла выключен, ток ограничен.
        /// </summary>
        internal static string VectorMode {
            get {
                return ResourceManager.GetString("VectorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия программы:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь, что колесо может свободно вращаться. Продолжить?.
        /// </summary>
        internal static string WheelCanTurn {
            get {
                return ResourceManager.GetString("WheelCanTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное задание сдвига фазы может привести к выходу контроллера или двигателя из строя. Это не является гарантийным случаем. Продолжить?.
        /// </summary>
        internal static string WrongShift {
            get {
                return ResourceManager.GetString("WrongShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таймаут нулевой скорости (7).
        /// </summary>
        internal static string ZeroSpeedTimeOut {
            get {
                return ResourceManager.GetString("ZeroSpeedTimeOut", resourceCulture);
            }
        }
    }
}
